variable "resource_group" {}
variable "virtual_networks" {}
variable "network_interfaces" {}
variable "public_ip" {}
variable "key-vaults" {}
variable "nsg" {}
variable "bastion" {}
variable "storage_accounts" {}
variable "storage_containers" {}
variable "postgresql_servers" {}
variable "postgresql_databases" {}
variable "sql_servers" {}
variable "sql_databases" {}
variable "private_endpoints" {}
variable "log_analytics_workspaces" {}
variable "app_gateways" {}
variable "load_balancers" {}
variable "aks_clusters" {}
variable "container_registries" {}
variable "application_security_groups" {}