trigger: 
- main

pool: 
  vmImage: ubuntu-latest

variables:
  workDir: '$(System.DefaultWorkingDirectory)/Root/Dev-Env'

stages:
- stage: Build
  displayName: Build
  jobs:       
  - job: TerraformInitPlan
    displayName: Terraform Init and Plan Job
    steps: 
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workDir)
        backendServiceArm: 'My-ARM'
        backendAzureRmResourceGroupName: 'Backend-detail'
        backendAzureRmStorageAccountName: 'stgprince15942'
        backendAzureRmContainerName: 'cntprince'
        backendAzureRmKey: 'ttt.tfstate'

    - task: TerraformTask@5
      displayName: plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(workDir)
        environmentServiceNameAzureRM: 'My-ARM'

- stage: validation
  displayName: validation
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs: 
  - job: ManualValidation
    displayName: Manual Validation kardo Please
    pool: server
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'prince.nagar22@gmail.com'
        approvers: 'prince.nagar22@gmail.com'
        instructions: 'Plan check karo'

- stage: deploy
  dependsOn: validation
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
    - job: TerraformApply
      displayName: Terraform Apply wala Job
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: $(workDir)
          backendServiceArm: 'My-ARM'
          backendAzureRmResourceGroupName: 'Backend-detail'
          backendAzureRmStorageAccountName: 'stgprince15942'
          backendAzureRmContainerName: 'cntprince'
          backendAzureRmKey: 'ttt.tfstate'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: $(workDir)
          environmentServiceNameAzureRM: 'My-ARM'

