# pipelines/dev.yaml

trigger:
  # - Feature/*
  - none
  
variables:
  workDir: '$(System.DefaultWorkingDirectory)/Root/Dev-Env'

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: TerraformInitPlan
        displayName: Terraform Init and Plan Job
        pool:
          name: 'Default' # your self-hosted agent pool
        steps:
          # Install Terraform CLI
          - task: TerraformInstaller@1
            displayName: Install Terraform (latest)
            inputs:
              terraformVersion: 'latest'

          # Terraform Init with remote backend
          - task: TerraformTask@5
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'ARM-Prince'
              backendAzureRmResourceGroupName: 'rg-prince-state'
              backendAzureRmStorageAccountName: 'stgprince3862'
              backendAzureRmContainerName: 'cntprince6592'
              backendAzureRmKey: 'ttt.tfstate'
              workingDirectory: '$(workDir)'

          # Terraform Plan
          - task: TerraformTask@5
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'ARM-Prince'
              workingDirectory: '$(workDir)'

  - stage: Deploy
    displayName: Deploy
    dependsOn: Build
    # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    condition: succeeded()
    jobs:
      - job: TerraformApply
        displayName: Terraform Apply Job
        pool:
          name: 'Default' # your self-hosted agent pool
        steps:
          # Re-run init to ensure backend is ready
          - task: TerraformInstaller@1
            displayName: Install Terraform (latest)
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'ARM-Prince'
              backendAzureRmResourceGroupName: 'rg-prince-state'
              backendAzureRmStorageAccountName: 'stgprince3862'
              backendAzureRmContainerName: 'cntprince6592'
              backendAzureRmKey: 'ttt.tfstate'
              workingDirectory: '$(workDir)'

          # Terraform Apply
          - task: TerraformTask@5
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'ARM-Prince'
              workingDirectory: '$(workDir)'
