trigger:
  - none
  
variables:
  workDir: '$(System.DefaultWorkingDirectory)/Root/Dev-Env'

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: TerraformInitPlan
        displayName: Terraform Init and Plan Job
        pool:
          name: 'Default'
        steps:
          - task: TerraformInstaller@1
            displayName: Install Terraform (latest)
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'ARM-Prince'
              backendAzureRmResourceGroupName: 'all-resources-group'
              backendAzureRmStorageAccountName: 'stgprince20242'
              backendAzureRmContainerName: 'cntprince22777'
              backendAzureRmKey: 'ttt.tfstate'
              workingDirectory: '$(workDir)'

          - task: TerraformTask@5
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'ARM-Prince'
              workingDirectory: '$(workDir)'

  - stage: Deploy
    displayName: Deploy
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: TerraformApply
        displayName: Terraform Apply Job
        pool:
          name: 'Default'
        steps:
          - task: TerraformInstaller@1
            displayName: Install Terraform (latest)
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'ARM-Prince'
              backendAzureRmResourceGroupName: 'all-resources-group'
              backendAzureRmStorageAccountName: 'stgprince20242'
              backendAzureRmContainerName: 'cntprince22777'
              backendAzureRmKey: 'ttt.tfstate'
              workingDirectory: '$(workDir)'

          - task: TerraformTask@5
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'ARM-Prince'
              workingDirectory: '$(workDir)'
